# Generated by Django 5.0.2 on 2024-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_alter_settings_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
