# Generated by Django 5.0.2 on 2024-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_banner_type_alter_banner_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(blank=True, choices=[('Header', 'Header'), ('Footer', 'Footer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
