# Generated by Django 5.0.2 on 2024-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_banner_banner_type_alter_banner_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
