# Generated by Django 5.0.2 on 2024-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_banner_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
