# Generated by Django 5.0.2 on 2024-03-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_brand_alter_product_category_and_more'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.tools'),
        ),
    ]
